/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.whatsapp;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author togae
 */
public class ConfiguracionUsuario extends javax.swing.JFrame {

    private Usuario u = new Usuario();
    private Encriptacion e = new Encriptacion();

    /**
     * Creates new form ConfiguracionUsuario
     */
    public ConfiguracionUsuario() {
        initComponents();
        setImagenRegresar();
        setSexo();
        this.setLocationRelativeTo(this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCambiarTodo = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jLabelFotoUsuario = new javax.swing.JLabel();
        jLabelNuevoSexo = new javax.swing.JLabel();
        jRadioButtonCambiarSexoMujer = new javax.swing.JRadioButton();
        jRadioButtonCambiarSexoHombre = new javax.swing.JRadioButton();
        jLabelNuevaContraseña = new javax.swing.JLabel();
        jTextFieldNuevaContraseña = new javax.swing.JTextField();
        jButtonCambiarContraseña = new javax.swing.JButton();
        jLabelNuevoTelefono = new javax.swing.JLabel();
        jTextFieldNuevoTelefono = new javax.swing.JTextField();
        jButtonCambiarTelefono = new javax.swing.JButton();
        jLabelNuevoNombre = new javax.swing.JLabel();
        jTextFieldNuevoNombre = new javax.swing.JTextField();
        jButtonCambiarNombre = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCambiarTodo.setBackground(new java.awt.Color(204, 51, 0));
        jButtonCambiarTodo.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jButtonCambiarTodo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarTodo.setText("Cambiar Todo");
        jButtonCambiarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarTodoMouseClicked(evt);
            }
        });
        jButtonCambiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, 40));

        jButtonRegresar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRegresar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseClicked(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jButtonSalida.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 50));
        getContentPane().add(jLabelFotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, 140));

        jLabelNuevoSexo.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelNuevoSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevoSexo.setText("Seleccione el Sexo:");
        getContentPane().add(jLabelNuevoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 370, -1));

        jRadioButtonCambiarSexoMujer.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jRadioButtonCambiarSexoMujer.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCambiarSexoMujer.setText("Femenino");
        jRadioButtonCambiarSexoMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCambiarSexoMujerActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCambiarSexoMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 170, 40));

        jRadioButtonCambiarSexoHombre.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jRadioButtonCambiarSexoHombre.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCambiarSexoHombre.setText("Masculino");
        jRadioButtonCambiarSexoHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCambiarSexoHombreActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCambiarSexoHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 170, 40));

        jLabelNuevaContraseña.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelNuevaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevaContraseña.setText("Digite la Nueva Contraseña:");
        getContentPane().add(jLabelNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 370, -1));

        jTextFieldNuevaContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNuevaContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 40));

        jButtonCambiarContraseña.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCambiarContraseña.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jButtonCambiarContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCambiarContraseña.setText("Cambiar");
        jButtonCambiarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarContraseñaMouseClicked(evt);
            }
        });
        jButtonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, 40));

        jLabelNuevoTelefono.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelNuevoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevoTelefono.setText("Digite el Nuevo Telefono:");
        getContentPane().add(jLabelNuevoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, -1));

        jTextFieldNuevoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNuevoTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNuevoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 250, 40));

        jButtonCambiarTelefono.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCambiarTelefono.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jButtonCambiarTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCambiarTelefono.setText("Cambiar");
        jButtonCambiarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarTelefonoMouseClicked(evt);
            }
        });
        jButtonCambiarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, 40));

        jLabelNuevoNombre.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelNuevoNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevoNombre.setText("Digite el Nuevo Nombre:");
        getContentPane().add(jLabelNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 310, -1));
        getContentPane().add(jTextFieldNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 40));

        jButtonCambiarNombre.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCambiarNombre.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jButtonCambiarNombre.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCambiarNombre.setText("Cambiar");
        jButtonCambiarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarNombreMouseClicked(evt);
            }
        });
        jButtonCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 40));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNegro.gif"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 696));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jTextFieldNuevoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevoTelefonoActionPerformed

    private void jTextFieldNuevaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevaContraseñaActionPerformed

    private void jRadioButtonCambiarSexoHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCambiarSexoHombreActionPerformed
        jRadioButtonCambiarSexoHombre.setSelected(true);
        jRadioButtonCambiarSexoMujer.setSelected(false);
        u.setNuevoSexo(false);
        setFotoLabelPerfil(false);
    }//GEN-LAST:event_jRadioButtonCambiarSexoHombreActionPerformed

    private void jRadioButtonCambiarSexoMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCambiarSexoMujerActionPerformed
        jRadioButtonCambiarSexoMujer.setSelected(true);
        jRadioButtonCambiarSexoHombre.setSelected(false);
        u.setNuevoSexo(true);
        setFotoLabelPerfil(true);
    }//GEN-LAST:event_jRadioButtonCambiarSexoMujerActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegresarMouseClicked

    private void jButtonCambiarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarNombreMouseClicked

    private void jButtonCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarNombreActionPerformed
        if (!jTextFieldNuevoNombre.getText().isEmpty()) {
            u.setNuevoNombreUsuario(e.Encriptamiento(jTextFieldNuevoNombre.getText()));
            JOptionPane.showMessageDialog(null, "El Nombre del Usuario se ha Cambiado Exitosamente!");
        } else {
            JOptionPane.showMessageDialog(null, "Nombre no valido!!");
        }
    }//GEN-LAST:event_jButtonCambiarNombreActionPerformed

    private void jButtonCambiarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarTelefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarTelefonoMouseClicked

    private void jButtonCambiarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarTelefonoActionPerformed
        if (!jTextFieldNuevoTelefono.getText().isEmpty()) {
            u.setNuevoTelefono(Integer.parseInt(jTextFieldNuevoTelefono.getText()));
            JOptionPane.showMessageDialog(null, "El Telefono del Usuario se ha Cambiado Exitosamente!");
        } else {
            JOptionPane.showMessageDialog(null, "Telefono no valido!!");
        }
    }//GEN-LAST:event_jButtonCambiarTelefonoActionPerformed

    private void jButtonCambiarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarContraseñaMouseClicked

    private void jButtonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaActionPerformed
        if (!jTextFieldNuevaContraseña.getText().isEmpty()) {
            u.setNuevaContraseña(e.Encriptamiento(jTextFieldNuevaContraseña.getText()));
            JOptionPane.showMessageDialog(null, "La Contraseña del Usuario se ha Cambiado Exitosamente!");
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña no valida!!");
        }
    }//GEN-LAST:event_jButtonCambiarContraseñaActionPerformed

    private void jButtonCambiarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarTodoMouseClicked
        boolean todoBien = true;
        if (!jTextFieldNuevoNombre.getText().isEmpty()) {
            u.setNuevoNombreUsuario(e.Encriptamiento(jTextFieldNuevoNombre.getText()));
        } else {
            todoBien = false;
            JOptionPane.showMessageDialog(null, "Nombre no valido!!");
        }
        if (!jTextFieldNuevaContraseña.getText().isEmpty()) {
            u.setNuevaContraseña(e.Encriptamiento(jTextFieldNuevaContraseña.getText()));
        } else {
            todoBien = false;
            JOptionPane.showMessageDialog(null, "Contraseña no valida!!");
        }
        if (!jTextFieldNuevoTelefono.getText().isEmpty()) {
            u.setNuevoTelefono(Integer.parseInt(jTextFieldNuevoTelefono.getText()));
        } else {
            todoBien = false;
            JOptionPane.showMessageDialog(null, "Telefono no valido!!");
        }
        if (todoBien) {
         JOptionPane.showMessageDialog(null, "Los datos del Usuario se ha Cambiado Exitosamente!");   
        }
    }//GEN-LAST:event_jButtonCambiarTodoMouseClicked

    private void jButtonCambiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarTodoActionPerformed
        
    }//GEN-LAST:event_jButtonCambiarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionUsuario().setVisible(true);
            }
        });
    }

    public void setFotoLabelPerfil(boolean sexo) {
        ImageIcon foto;
        if (sexo) {
            foto = new ImageIcon("src/main/resources/Imagenes/mujerU.png");
        } else {
            foto = new ImageIcon("src/main/resources/Imagenes/hombreU.png");
        }
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jLabelFotoUsuario.getWidth(), jLabelFotoUsuario.getHeight(), Image.SCALE_DEFAULT));
        jLabelFotoUsuario.setIcon(icon);
        this.repaint();
    }

    public void setImagenRegresar() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/Regresar.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonRegresar.getWidth(), jButtonRegresar.getHeight(), Image.SCALE_DEFAULT));
        jButtonRegresar.setIcon(icon);
        jButtonRegresar.setFocusPainted(false);
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        this.repaint();
    }

    public void setSexo() {
        if (u.getSexo()) {
            jRadioButtonCambiarSexoMujer.setSelected(true);
        } else {
            jRadioButtonCambiarSexoHombre.setSelected(true);
        }
        setFotoLabelPerfil(u.getSexo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarContraseña;
    private javax.swing.JButton jButtonCambiarNombre;
    private javax.swing.JButton jButtonCambiarTelefono;
    private javax.swing.JButton jButtonCambiarTodo;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelNuevaContraseña;
    private javax.swing.JLabel jLabelNuevoNombre;
    private javax.swing.JLabel jLabelNuevoSexo;
    private javax.swing.JLabel jLabelNuevoTelefono;
    private javax.swing.JRadioButton jRadioButtonCambiarSexoHombre;
    private javax.swing.JRadioButton jRadioButtonCambiarSexoMujer;
    private javax.swing.JTextField jTextFieldNuevaContraseña;
    private javax.swing.JTextField jTextFieldNuevoNombre;
    private javax.swing.JTextField jTextFieldNuevoTelefono;
    // End of variables declaration//GEN-END:variables
}
