/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.whatsapp;
import Interfaz.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author togae
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
        setFotoLabelPerfil();
        setImagenLogIn();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalida = new javax.swing.JButton();
        jButtonLogIn = new javax.swing.JButton();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelFotoPerfil = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelFondoVerde = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalida.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 40));

        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 240, 50));

        jTextFieldNombreUsuario.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextFieldNombreUsuario.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextFieldNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 50));

        jPasswordField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 310, 50));
        getContentPane().add(jLabelFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 170));

        jLabelContraseña.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 153, 102));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabelNombreUsuario.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(0, 153, 102));
        jLabelNombreUsuario.setText("Nombre del Usuario:");
        getContentPane().add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 281, -1, 40));

        jLabelFondoVerde.setBackground(java.awt.Color.white);
        jLabelFondoVerde.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelFondoVerde.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFondoVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzul.jpg"))); // NOI18N
        jLabelFondoVerde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 350, 280));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBlanco.jpg"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 696));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        Usuario u = new Usuario();
        if (jTextFieldNombreUsuario.getText().equalsIgnoreCase(u.getNombreUsuario()) && jPasswordField.getText().equals(u.getContraseña())) {
            this.setVisible(false);
            Menu m = new Menu();
            m.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "El Nombre del Usuario o la Contraseña son Incorrectas!!");
        }
    }//GEN-LAST:event_jButtonLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    
    public void setFotoLabelPerfil(){
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/Usuario.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jLabelFotoPerfil.getWidth(), jLabelFotoPerfil.getHeight(), Image.SCALE_DEFAULT));
        jLabelFotoPerfil.setIcon(icon);
        this.repaint();
    }
    public void setImagenLogIn(){
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/LogIn.jpg");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonLogIn.getWidth(), jButtonLogIn.getHeight(), Image.SCALE_DEFAULT));
        jButtonLogIn.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoVerde;
    private javax.swing.JLabel jLabelFotoPerfil;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
