/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.whatsapp;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javafx.scene.paint.Color;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author togae
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        setContactos();
        setFotoLabelBarra();
        setImagenLogOut();
        setImagenUsuario();
        setImagenConfigurarUsuario();
        setImagenNuevoContacto();
        setImagenChatear();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListContactos = new javax.swing.JList<>();
        jButtonLogOut = new javax.swing.JButton();
        jButtonNuevoContacto = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jButtonConfigurarUsuario = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jButtonChatear = new javax.swing.JButton();
        jLabelListaContactos = new javax.swing.JLabel();
        jLabelBarra = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListContactos.setBackground(new java.awt.Color(51, 51, 51));
        jListContactos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jListContactos.setFont(new java.awt.Font("Century Gothic", 3, 48)); // NOI18N
        jListContactos.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListContactos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 300, 400));

        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 60, 50));

        jButtonNuevoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoContactoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 60, 50));

        jButtonUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonUsuario.setForeground(new java.awt.Color(60, 63, 65));
        jButtonUsuario.setFocusCycleRoot(true);
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jButtonConfigurarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfigurarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConfigurarUsuarioMouseEntered(evt);
            }
        });
        jButtonConfigurarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigurarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfigurarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 50));

        jButtonSalida.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 50));

        jButtonChatear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChatearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChatear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 70, 70));

        jLabelListaContactos.setFont(new java.awt.Font("Bodoni MT Black", 3, 48)); // NOI18N
        jLabelListaContactos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListaContactos.setText("Contactos:");
        getContentPane().add(jLabelListaContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 300, -1));
        getContentPane().add(jLabelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNegro.gif"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 696));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        Usuario u = new Usuario();
        JOptionPane.showMessageDialog(null, u.toString());
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonConfigurarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigurarUsuarioActionPerformed
        Usuario u = new Usuario();
        String c = JOptionPane.showInputDialog("Digite su Contraseña:");
        if (u.getContraseña().equals(c)) {
            this.setVisible(false);
            ConfiguracionUsuario cu = new ConfiguracionUsuario();
            cu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La Contraseña es Incorrecta!!");
        }
    }//GEN-LAST:event_jButtonConfigurarUsuarioActionPerformed

    private void jButtonConfigurarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfigurarUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigurarUsuarioMouseEntered

    private void jButtonConfigurarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfigurarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigurarUsuarioMouseClicked

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        this.setVisible(false);
        InicioSesion s = new InicioSesion();
        s.setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonNuevoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoContactoActionPerformed
        this.setVisible(false);
        NuevoContacto s = new NuevoContacto();
        s.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoContactoActionPerformed

    private void jButtonChatearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChatearActionPerformed
        try {
            if (jListContactos.getSelectedValue() != null) {
                this.setVisible(false);
                Chat c = new Chat(String.valueOf(jListContactos.getSelectedValue()));
                c.setVisible(true);
            } else {
                int x = 1 / 0;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Primero debe Seleccionar un Contacto!!");
        }
    }//GEN-LAST:event_jButtonChatearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public void setFotoLabelBarra() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/Barra.jpeg");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jLabelBarra.getWidth(), jLabelBarra.getHeight(), Image.SCALE_DEFAULT));
        jLabelBarra.setIcon(icon);
        this.repaint();
    }

    public void setImagenUsuario() {
        Usuario u = new Usuario();
        ImageIcon foto;
        if (u.getSexo()) {
            foto = new ImageIcon("src/main/resources/Imagenes/mujerU.png");
        } else {
            foto = new ImageIcon("src/main/resources/Imagenes/hombreU.png");
        }
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonUsuario.getWidth(), jButtonUsuario.getHeight(), Image.SCALE_DEFAULT));
        jButtonUsuario.setIcon(icon);
        jButtonUsuario.setFocusPainted(false);
        jButtonUsuario.setBorderPainted(false);
        jButtonUsuario.setContentAreaFilled(false);
        this.repaint();
    }

    public void setImagenConfigurarUsuario() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/configuracion.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonConfigurarUsuario.getWidth(), jButtonConfigurarUsuario.getHeight(), Image.SCALE_DEFAULT));
        jButtonConfigurarUsuario.setIcon(icon);
        jButtonConfigurarUsuario.setFocusPainted(false);
        jButtonConfigurarUsuario.setBorderPainted(false);
        jButtonConfigurarUsuario.setContentAreaFilled(false);
        this.repaint();
    }

    public void setImagenNuevoContacto() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/NuevoContacto.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonNuevoContacto.getWidth(), jButtonNuevoContacto.getHeight(), Image.SCALE_DEFAULT));
        jButtonNuevoContacto.setIcon(icon);
        jButtonNuevoContacto.setFocusPainted(false);
        jButtonNuevoContacto.setBorderPainted(false);
        jButtonNuevoContacto.setContentAreaFilled(false);
        this.repaint();
    }

    public void setImagenLogOut() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/LogOut.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonLogOut.getWidth(), jButtonLogOut.getHeight(), Image.SCALE_DEFAULT));
        jButtonLogOut.setIcon(icon);
        jButtonLogOut.setFocusPainted(false);
        jButtonLogOut.setBorderPainted(false);
        jButtonLogOut.setContentAreaFilled(false);
        this.repaint();
    }

    public void setContactos() {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        Contactos c = new Contactos();
        LinkedList nombres = c.getNombreContactosJson();
        for (int i = 0; i < c.getNombreContactosJson().size(); i++) {
            modelo.addElement(String.valueOf(nombres.getFirst()));
            nombres.pop();
        }
        jListContactos.setModel(modelo);
    }

    public void setImagenChatear() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/chat.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonChatear.getWidth(), jButtonChatear.getHeight(), Image.SCALE_DEFAULT));
        jButtonChatear.setIcon(icon);
        jButtonChatear.setFocusPainted(false);
        jButtonChatear.setBorderPainted(false);
        jButtonChatear.setContentAreaFilled(false);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChatear;
    private javax.swing.JButton jButtonConfigurarUsuario;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonNuevoContacto;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabelBarra;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelListaContactos;
    private javax.swing.JList<String> jListContactos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
