/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.whatsapp;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author togae
 */
public class NuevoContacto extends javax.swing.JFrame {

    private boolean sexo = false;

    /**
     * Creates new form NuevoContacto
     */
    public NuevoContacto() {
        initComponents();
        setImagenRegresar();
        setFotoLabelPerfil(sexo);
        jRadioButtonContactoSexoHombre.setSelected(true);
        this.setLocationRelativeTo(this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonCambiarSexoHombre = new javax.swing.JRadioButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jRadioButtonContactoSexoMujer = new javax.swing.JRadioButton();
        jRadioButtonContactoSexoHombre = new javax.swing.JRadioButton();
        jButtonCambiarTodo = new javax.swing.JButton();
        jLabelFotoContacto = new javax.swing.JLabel();
        jLabelContactoSexo = new javax.swing.JLabel();
        jTextFieldContactoTelefono = new javax.swing.JTextField();
        jLabelContactoTelefono = new javax.swing.JLabel();
        jTextFieldContactoNombre = new javax.swing.JTextField();
        jLabelContactoNombre = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jRadioButtonCambiarSexoHombre.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jRadioButtonCambiarSexoHombre.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCambiarSexoHombre.setText("Masculino");
        jRadioButtonCambiarSexoHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCambiarSexoHombreActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRegresar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseClicked(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jButtonSalida.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 50));

        jRadioButtonContactoSexoMujer.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jRadioButtonContactoSexoMujer.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonContactoSexoMujer.setText("Femenino");
        jRadioButtonContactoSexoMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonContactoSexoMujerActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonContactoSexoMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 170, 40));

        jRadioButtonContactoSexoHombre.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jRadioButtonContactoSexoHombre.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonContactoSexoHombre.setText("Masculino");
        jRadioButtonContactoSexoHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonContactoSexoHombreActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonContactoSexoHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 40));

        jButtonCambiarTodo.setBackground(new java.awt.Color(204, 51, 0));
        jButtonCambiarTodo.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jButtonCambiarTodo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarTodo.setText("Agrgar Contacto");
        jButtonCambiarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarTodoMouseClicked(evt);
            }
        });
        jButtonCambiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, 50));
        getContentPane().add(jLabelFotoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, 140));

        jLabelContactoSexo.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelContactoSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContactoSexo.setText("Seleccione el Sexo del Contacto:");
        getContentPane().add(jLabelContactoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 390, -1));
        getContentPane().add(jTextFieldContactoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 360, 40));

        jLabelContactoTelefono.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelContactoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContactoTelefono.setText("Digite el Telefono del Contacto:");
        getContentPane().add(jLabelContactoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, -1));

        jTextFieldContactoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldContactoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 360, 40));

        jLabelContactoNombre.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabelContactoNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContactoNombre.setText("Digite el Nombre del Contacto:");
        getContentPane().add(jLabelContactoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, -1));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNegro.gif"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 696));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegresarMouseClicked

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jRadioButtonCambiarSexoHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCambiarSexoHombreActionPerformed


    }//GEN-LAST:event_jRadioButtonCambiarSexoHombreActionPerformed

    private void jRadioButtonContactoSexoHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonContactoSexoHombreActionPerformed
        jRadioButtonContactoSexoHombre.setSelected(true);
        jRadioButtonContactoSexoMujer.setSelected(false);
        setFotoLabelPerfil(false);
        sexo = false;
    }//GEN-LAST:event_jRadioButtonContactoSexoHombreActionPerformed

    private void jRadioButtonContactoSexoMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonContactoSexoMujerActionPerformed
        jRadioButtonContactoSexoMujer.setSelected(true);
        jRadioButtonContactoSexoHombre.setSelected(false);
        setFotoLabelPerfil(true);
        sexo = true;
    }//GEN-LAST:event_jRadioButtonContactoSexoMujerActionPerformed

    private void jButtonCambiarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarTodoMouseClicked

    }//GEN-LAST:event_jButtonCambiarTodoMouseClicked

    private void jButtonCambiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarTodoActionPerformed
        boolean todoBien = true;
        if (jLabelContactoNombre.getText().isEmpty()) {
            todoBien = false;
            JOptionPane.showMessageDialog(null, "Nombre no valido!!");
        }
        if (jTextFieldContactoTelefono.getText().isEmpty()) {
            todoBien = false;
            JOptionPane.showMessageDialog(null, "Telefono no valido!!");
        }
        if (todoBien) {
            Contactos c = new Contactos(String.valueOf(jTextFieldContactoNombre.getText()),Integer.parseInt(String.valueOf(jTextFieldContactoTelefono.getText())),sexo);
            Mensajes m = new Mensajes();
            m.Reset("Mensajes"+String.valueOf(jTextFieldContactoNombre.getText()));
            JOptionPane.showMessageDialog(null, "El Nuevo Contacto se ha Creado Exitosamente!");
        }
    }//GEN-LAST:event_jButtonCambiarTodoActionPerformed

    private void jTextFieldContactoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactoNombreActionPerformed

    }//GEN-LAST:event_jTextFieldContactoNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoContacto().setVisible(true);
            }
        });
    }

    public void setFotoLabelPerfil(boolean sexo) {
        ImageIcon foto;
        if (sexo) {
            foto = new ImageIcon("src/main/resources/Imagenes/mujerU.png");
        } else {
            foto = new ImageIcon("src/main/resources/Imagenes/hombreU.png");
        }
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jLabelFotoContacto.getWidth(), jLabelFotoContacto.getHeight(), Image.SCALE_DEFAULT));
        jLabelFotoContacto.setIcon(icon);
        this.repaint();
    }

    public void setImagenRegresar() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/Regresar.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonRegresar.getWidth(), jButtonRegresar.getHeight(), Image.SCALE_DEFAULT));
        jButtonRegresar.setIcon(icon);
        jButtonRegresar.setFocusPainted(false);
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarTodo;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelContactoNombre;
    private javax.swing.JLabel jLabelContactoSexo;
    private javax.swing.JLabel jLabelContactoTelefono;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFotoContacto;
    private javax.swing.JRadioButton jRadioButtonCambiarSexoHombre;
    private javax.swing.JRadioButton jRadioButtonContactoSexoHombre;
    private javax.swing.JRadioButton jRadioButtonContactoSexoMujer;
    private javax.swing.JTextField jTextFieldContactoNombre;
    private javax.swing.JTextField jTextFieldContactoTelefono;
    // End of variables declaration//GEN-END:variables
}
